version: "3.6"

services:
  netbeans-builder:
    image: frekele/ant:1.10.3-jdk8
    container_name: netbeans-builder
    command: ant -buildfile /project/build.xml -Dcluster.config=standard
    volumes:
      - ${PWD}:/project